version: "3.8"

networks:
  desafio-network:
    driver: bridge

services:
  desafio-db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    networks:
      - desafio-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - desafio-db-data:/var/lib/postgresql/data
  
  desafio-api:
    build:
      context: ../desafio-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    networks:
      - desafio-network
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      TZ: ${TZ}
    depends_on:
      - desafio-db
 
  desafio-web:
    build:
      context: ../desafio-web
    restart: always
    ports:
      - "4000:80"
    networks:
      - desafio-network
    depends_on:
      - desafio-api

volumes:
  desafio-db-data:
    external: false
